In [2]:
import numpy as np

In [3]:
x = np.array([4, 7, 9])
y = np.array([78, 43, 90])
z = [54, 3, 7]

grid = np.array([y, z])
print(grid)

vert_stack = np.vstack([x, grid])
print("Vertically stacked \n", vert_stack)

#splitting things up
split_array_row2 = np.split(vert_stack, [2])
print("Did this wrong!\n Splitting things up: \n", split_array_row2)

#vertically splitting things up
vert_split_array_1, vert_split_array_2  = np.vsplit(vert_stack, [2])
print("VERTICALLY Splitting things up: \n", vert_split_array_1, "\n\n", vert_split_array_2)

#horizontally splitting things up\n",
horz_split_array_1, horz_split_array_2  = np.hsplit(vert_stack, [2])

[[78 43 90]
 [54  3  7]]
Vertically stacked 
 [[ 4  7  9]
 [78 43 90]
 [54  3  7]]
Did this wrong!
 Splitting things up: 
 [array([[ 4,  7,  9],
       [78, 43, 90]]), array([[54,  3,  7]])]
VERTICALLY Splitting things up: 
 [[ 4  7  9]
 [78 43 90]] 

 [[54  3  7]]


In [53]:
x = np.array([4, 7, 9])
y = np.array([78, 43, 90])
z = [54, 3, 7]
grid = np.array([y, z])
print(grid)

vert_stack = np.vstack([x, grid])
print("Vertically stacked \n", vert_stack)

right = np.array([[4], [6]])
horz_stack = np.hstack([grid, right])
print("Vertically stacked \n", horz_stack)

[[78 43 90]
 [54  3  7]]
Vertically stacked 
 [[ 4  7  9]
 [78 43 90]
 [54  3  7]]
Vertically stacked 
 [[78 43 90  4]
 [54  3  7  6]]


In [45]:
x = np.array([4, 7, 9])
y = np.array([78, 43, 90])
z = [54, 3, 7]

big_cat = np.concatenate([x, y, z])
print("Big \n",big_cat)

twod_cat = np.concatenate([[x, y]])
print("2D \n", twod_cat)

twod_row_cat = np.concatenate([[x], [y]], axis=0)
print("2D by row \n", twod_row_cat)

twod_col_cat = np.concatenate([[x], [y]], axis=1)
print("2D by column \n", twod_col_cat)

threed_cat = np.concatenate([[[x, y, z],[x, y, z]]])
print("3D Array maybe? \n",threed_cat)

Big 
 [ 4  7  9 78 43 90 54  3  7]
2D 
 [[ 4  7  9]
 [78 43 90]]
2D by row 
 [[ 4  7  9]
 [78 43 90]]
2D by column 
 [[ 4  7  9 78 43 90]]
3D Array maybe? 
 [[[ 4  7  9]
  [78 43 90]
  [54  3  7]]

 [[ 4  7  9]
  [78 43 90]
  [54  3  7]]]


In [22]:
#reshaping and newaxis
x = np.array([1, 4, 6, 3, 5, 8])
y = x.reshape((2,3))
print(y)

z = y[:, np.newaxis]
print(z)


[[1 4 6]
 [3 5 8]]
[[[1 4 6]]

 [[3 5 8]]]
